spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/selection_bd?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    properties:

      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
file:
  upload-dir: ./files
