spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://localhost:8889/selection_bd?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    properties:

      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always


